### ISSUE TITLE
I2. Evaluate the improved domain-layer's aDSL(s)

### ISSUE THREAD

**Issue by ducmle** [jdomainapp/jda#38]
Depends on: #37 
**Paper-1 [mbsl](/jdomainapp/doc-mbsl): Part 3**
@hanhdd 

- [x] evaluate the effectiveness of the aDSL(s) for the **domain model layer**
- [ ] Complete the journal paper ISI (Q1-2) about the result (in progress, and see below)

# Case study: OrderMan
@levanvinhskv 
**Tasks:**
- [ ] AGL: allow user to execute or resume execution of a node of an activity at a later time
   - Example (see image below):  Nodes 8 and 9 are usually not executed at them time the activity. Note that they still need to be executed in parallel.
![orderman-design-agl drawio](https://user-images.githubusercontent.com/23070975/227075921-fbb4e9a7-5b28-42bc-959b-722ce7699fde.png)
