### ISSUE TITLE
jdafs-tool

### ISSUE THREAD

**Issue by ducmle** [jdomainapp/jda#59]
## Dependencies: 
- #17 
- #16 

## Development
- Code branch: [f59](https://github.com/jdomainapp/jda/tree/f59)
## Overview
This is the programming-user-friendly version of the SwGen component. It uses the components of SwGen but provides a somewhat simplified programming API so that novice programming users (such as 1st year students) can learn to create software by following the domain-driven approach. 

A typical scenario is as follows. The user would focus on defining the domain model (using DCSL) and the tool would take this model as input and generate an fullstack executable software as the output. The idea is that the user would see the domain model realised in the software, test it and improve the domain model. This is repeated until the domain model satisfies the requirements.

`jdafs-tool` is developed as an extension of the existing DomainAppTool component of jda. This component, however, only supports the Java Swing UI. `jdafs-tool` is designed to support web-based and mobile front-ends. It is built on the current fullstack implementation of the module `jda-mosar`.

## Tasks
- [ ] #97
- [ ] #98
- [ ] #96
- [ ] Check that the generated software matches the benchmark app. Repeat tasks 1-3 if needed.
- [ ] Implement web-based version of `jdafs-tool`. Default front end: React.js; back end: SpringBoot
- [ ] Evaluate `jdafs-tool`:
   - [ ] Correctness: correctly generate four types of FE
   - [ ] Deployment: ease of deployment and execution of the app
   - [ ] Modifiability: ease of module update
   - [ ] Usability: against core UI/UX design patterns
