### ISSUE TITLE
MSA-based SwConstructor

### ISSUE THREAD

**Issue by ducmle** [jdomainapp/jda#90]
@congnv8192 (assigned)

## Overview
The aim of this project is to implement the MSA-based software constructor module. This module is part of the MDSD-AL research project.

Technically, the software constructor is to be extended from the existing SwGen component in JDA.

## Tasks
- [x] Implement TASL as part of jda.modules.tmsa: https://github.com/jdomainapp/jda/tree/main/modules/mdsa/src/main/java/jda/modules/tmsa
- [x] Adapt MOSAR design for microservice controllers. Using `SoftwareImplement` class for database handling
- [x] Implement the generator, scalable to support different platforms
   - [x] implement for Spring Boot
   - [ ] Implement for Nodejs
- [ ] Test generator
   - [ ] module: address
   - [ ] module: student (enrolment)
   - [ ] module: coursemodule
   - [ ] module: studentClass (student -> address)
- [ ]
